media:
  input: public/blog-images
  output: /blog-images
content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [title, publishDate, draft]
    fields:
      - { name: title, label: Title, type: string }
      - { name: excerpt, label: Excerpt, type: text }
      - { name: publishDate, label: Publish Date, type: date }
      - { name: image, label: Image, type: image }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Body, type: rich-text }
